backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: public/images
public_folder: /images

site_url: https://www.enoa.gr
display_url: https://www.enoa.gr
logo_url: /images/enoa-logo-white.png

locale: el

collections:
  - name: pages
    label: Σελίδες
    folder: content/pages
    create: true
    slug: "{{slug}}"
    fields:
      - label: Τίτλος
        name: title
        widget: string
      - label: Κείμενο
        name: body
        widget: markdown

  - name: news
    label: Νέα
    folder: content/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Τίτλος
        name: title
        widget: string
      - label: Περίληψη
        name: excerpt
        widget: text
      - label: Εικόνα
        name: image
        widget: image
      - label: Ημερομηνία
        name: publishDate
        widget: datetime
      - label: Κείμενο
        name: body
        widget: markdown

  - name: sports
    label: Αθλήματα
    folder: content/sports
    create: true
    slug: "{{slug}}"
    fields:
      - label: Όνομα
        name: title
        widget: string
      - label: Περιγραφή
        name: description
        widget: text
      - label: Εικόνα
        name: image
        widget: image
      - label: Κείμενο
        name: body
        widget: markdown